### ISSUE TITLE
是否支持多卡训练？

### ISSUE THREAD

**Issue by Senwang98** [louis-she/minetorch#52]

**Comment by louis-she** [comment]
目前会自动使用 nn.DataParallel 的方式使用多卡
但实际上 DistributedParallel 更合适，但暂时没有更新计划

**Comment by Senwang98** [comment]
@louis-she 
可是似乎minetorch我这边训练的时候不会均摊batch到每一张卡上面，请问有什么传参可以设置吗？

**Comment by louis-she** [comment]
如果机器有多张显卡，MineTorch 会自动使用 nn.DataParallel 的方式多卡训练，不需要做设置

**Comment by Senwang98** [comment]
这很奇怪，我这边似乎并不能多卡运行，log文件会告诉我 `will use all gpu`，同时我在你源码找到了DataParallel，尽管确实device-count=8，但是最终似乎还是不能多卡运行。
我排除过服务器的问题，随便写的一个model的话自己写DataParallel，是可以多卡的，挺迷的

**Comment by YZY-stack** [comment]
@Senwang98 您好， 我遇到了同样的问题，请问您已经解决了吗？我设置了gpu=True，log里面也是will use all，but实际中nvidia-smi中只看到了一张卡在跑

**Comment by YZY-stack** [comment]
> @Senwang98 您好， 我遇到了同样的问题，请问您已经解决了吗？我设置了gpu=True，log里面也是will use all，but实际中nvidia-smi中只看到了一张卡在跑

hi，我刚跑起来，问题出在：forward_fn是我在外面写好传进去的，如果设成None，然后在minetorch源码里面的529行的forward函数里面改就work了

**Comment by Senwang98** [comment]
@YZY-stack 
感谢老哥，我这边后续自己写训练了哈哈哈，不过感谢你的debug
